# Generated by Django 4.0 on 2022-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_model',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productos_model',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
