# Generated by Django 4.0 on 2021-12-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services_model',
            options={'verbose_name': 'Servicios'},
        ),
    ]
