# Generated by Django 4.0 on 2021-12-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_services_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services_model',
            options={'verbose_name': 'Servicio'},
        ),
    ]
