# Generated by Django 4.0 on 2021-12-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_services_model_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services_model',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
