# Generated by Django 4.0 on 2021-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_services_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_model',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
