# Generated by Django 4.0 on 2021-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_alter_services_model_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_model',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
