# Generated by Django 4.0 on 2021-12-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_alter_services_model_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services_model',
            old_name='titlo',
            new_name='titulo',
        ),
    ]
