# Generated by Django 4.0 on 2022-01-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_rename_titlo_services_model_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_model',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
