# Generated by Django 4.0 on 2021-12-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts_model',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
